### ISSUE TITLE
Lando Docker WSL2 Issue

### ISSUE THREAD

**Issue by GravlLift** [lando/core#37]
I'm running Lando 3.11 on Windows 11 with WSL2. When I attempt to run any command, I get `WARN ==> docker is not running!`, despite docker desktop already running. If I run with `-vvvv` I see.

```
lando        11:25:56 DEBUG ==> engine is down with error message=errors pretty printing info
, stack=Error: errors pretty printing info

    at /snapshot/cli/node_modules/@lando/core/lib/shell.js
    at processImmediate (node:internal/timers:466:21)
From previous event:
    at Shell.sh (/snapshot/cli/node_modules/@lando/core/lib/shell.js)
    at LandoDaemon.isUp (/snapshot/cli/node_modules/@lando/core/lib/daemon.js)
    at /snapshot/cli/lib/cli.js
From previous event:
    at /snapshot/cli/lib/cli.js
    at processImmediate (node:internal/timers:466:21)
From previous event:
    at Object.handler (/snapshot/cli/lib/cli.js)
    at Object.runCommand (/snapshot/cli/node_modules/yargs/lib/command.js:238:44)
    at Object.parseArgs [as _parseArgs] (/snapshot/cli/node_modules/yargs/yargs.js:1063:30)
    at Function.get [as argv] (/snapshot/cli/node_modules/yargs/yargs.js:1004:21)
    at Cli.init (/snapshot/cli/lib/cli.js)
    at Cli.run (/snapshot/cli/lib/cli.js)
    at Object.<anonymous> (/snapshot/cli/bin/lando.js)
    at Module._compile (pkg/prelude/bootstrap.js:1887:22)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.runMain (pkg/prelude/bootstrap.js:1940:12)
    at node:internal/main/run_main_module:17:47, __stackCleaned__=true
```

Looking at the source, the call to `isUp` mentioned by the stack there is trying to run the command `docker info` to determine the state of docker.

https://github.com/lando/core/blob/e962924a392d436d7f7f2d9b69bfa707e3425122/lib/daemon.js#L159-L172

Docker's spitting out the associated error. But I have no problem running `docker info` in the same terminal window where lando is failing.

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc., v0.10.0)
  compose: Docker Compose (Docker Inc., v2.15.1)
  dev: Docker Dev Environments (Docker Inc., v0.0.5)
  extension: Manages Docker extensions (Docker Inc., v0.2.17)
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc., 0.6.0)
  scan: Docker Scan (Docker Inc., v0.23.0)

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 9
 Server Version: 20.10.22
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 9ba4b250366a5ddde94bb7c9d1def331423aa323
 runc version: v1.1.4-0-g5fd4c4d
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.15.90.1-microsoft-standard-WSL2
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 16
 Total Memory: 15.6GiB
 Name: docker-desktop
 ID: CRKN:C2FB:BXSO:654M:7SDL:POMC:2EKE:MPID:VYLR:FG7I:5YO6:27AG
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5000
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No blkio throttle.read_bps_device support
WARNING: No blkio throttle.write_bps_device support
WARNING: No blkio throttle.read_iops_device support
WARNING: No blkio throttle.write_iops_device support
```

Any idea what I'm doing wrong here?

**Comment by GravlLift** [comment]
Cloned the repo and stepped through with the debugger, the stdout of the command reveals a little more detail, but not much...

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc., v0.10.0)
  compose: Docker Compose (Docker Inc., v2.15.1)
  dev: Docker Dev Environments (Docker Inc., v0.0.5)
  extension: Manages Docker extensions (Docker Inc., v0.2.17)
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc., 0.6.0)
  scan: Docker Scan (Docker Inc., v0.23.0)

Server:
ERROR: Cannot connect to the Docker daemon at tcp://localhost:2375. Is the docker daemon running?
```

The docker daemon is indeed running and reachable as I can run the command from outside lando without issue.

**Comment by GravlLift** [comment]
If anyone comes across this issue, make sure to pay extra attention to the configuration steps on the [Windows WSL2 Setup Guide](https://docs.lando.dev/guides/setup-lando-on-windows-with-wsl-2.html). Any slight misconfiguration will leave you spinning your wheels like I was.
